import { z } from 'zod';

import type {
  ScreenStocksResponse,
  StockFilter,
  StockFilterOptions,
} from './stock-screener-types.js';

const range = z.looseObject({ minValue: z.number().optional(), maxValue: z.number().optional() });
const rangeFields = [
  'priceEarningsRatio',
  'marketCapitalization',
  'ownersChangeOneDay',
  'ownersChangeOneWeek',
  'ownersChangeOneMonth',
  'ownersChangeThreeMonths',
  'ownersChangeThisYear',
  'ownersChangeOneYear',
  'ownersChangeOneDayAbsolute',
  'ownersChangeOneWeekAbsolute',
  'ownersChangeOneMonthAbsolute',
  'ownersChangeThreeMonthsAbsolute',
  'ownersChangeThisYearAbsolute',
  'ownersChangeOneYearAbsolute',
  'priceDevelopmentToday',
  'priceDevelopmentOneMonth',
  'priceDevelopmentThreeMonths',
  'priceDevelopmentThisYear',
  'priceDevelopmentOneYear',
  'priceDevelopmentThreeYears',
  'priceDevelopmentFiveYears',
  'priceDevelopmentTenYears',
  'directYieldRatio',
  'dividendRatio',
  'dividendsPerYear',
  'dividendPerShare',
  'nextDividend',
  'shortSellingRatio',
  'collateralValue',
  'nextCompanyReport',
  'earningsPerShare',
  'turnoverPerShare',
  'profitMargin',
  'debtToEquityRatio',
  'bollingerDistanceUpperToLower',
  'bollingerDistanceLower',
  'bollingerDistanceUpper',
  'rsi14',
  'sma20',
  'sma50',
  'sma200',
  'smaBetween50and200',
  'rsiTrendThreeDays',
  'rsiTrendFiveDays',
  'equityPerShare',
  'priceSalesRatio',
  'priceBookRatio',
  'beta',
  'volatility',
  'returnOnEquity',
  'returnOnCapitalEmployed',
  'returnOnAssets',
  'operatingCashFlow',
  'netDebtEbitdaRatio',
  'evEbit',
  'macdValue',
  'macdHistogram',
  'macdSignal',
] as const;

export const stockFilterSchema: z.ZodType<StockFilter> = z.looseObject({
  sectors: z.array(z.string()).optional(),
  marketPlaces: z.array(z.string()).optional(),
  countryCodes: z.array(z.string()).optional(),
  marketPlaceCodes: z.array(z.string()).optional(),
  nameQuery: z.string().optional(),
  numberOfOwners: range.optional(),
  onlyDirectYield: z.boolean().optional(),
  onlyHasAnalysis: z.boolean().optional(),
  onlySuperloanApproved: z.boolean().optional(),
  ...Object.fromEntries(rangeFields.map((field) => [field, range.optional()])),
});

const option: z.ZodType<StockFilterOptions['sectors'][number]> = z.lazy(() =>
  z.looseObject({
    value: z.string(),
    displayName: z.string(),
    numberOfOrderbooks: z.string(),
    children: z.array(option).optional(),
  }),
);

export const stockFilterOptionsSchema: z.ZodType<StockFilterOptions> = z.looseObject({
  countryCodes: z.array(option),
  marketPlaces: z.array(option),
  sectors: z.array(option),
});

const metricNames = [
  'directYield',
  'priceEarningsRatio',
  'lastPrice',
  'highestPrice',
  'lowestPrice',
  'buyPrice',
  'sellPrice',
  'totalValueTraded',
  'totalVolumeTraded',
  'lastPriceUpdated',
  'oneDayChangePercent',
  'oneWeekChangePercent',
  'startOfYearChangePercent',
  'oneYearChangePercent',
  'oneMonthChangePercent',
  'threeMonthsChangePercent',
  'sixMonthsChangePercent',
  'threeYearsChangePercent',
  'fiveYearsChangePercent',
  'tenYearsChangePercent',
  'infinityChangePercent',
  'numberOfOwners',
  'shortSellingRatio',
  'evEbitRatio',
  'netDebtEbitdaRatio',
  'pricePerSaleRatio',
  'priceSalesRatio',
  'returnOnEquity',
  'returnOnAssets',
  'returnOnCapitalEmployed',
  'priceBookRatio',
  'earningsPerShare',
  'dividendPerShare',
  'equityPerShare',
  'dividendRatio',
  'turnoverPerShare',
  'marketCapitalization',
  'marketCap',
  'beta',
  'volatility',
  'sma20',
  'sma50',
  'sma200',
  'smaBetween50and200',
  'rsi14',
  'rsiTrendThreeDays',
  'rsiTrendFiveDays',
  'bollingerDistanceUpperToLower',
  'bollingerDistanceUpper',
  'bollingerDistanceLower',
  'collateralValue',
  'dividendsPerYear',
  'debtToEquityRatio',
  'profitMargin',
  'sales',
  'totalAssets',
  'totalLiabilities',
  'netProfit',
  'ownersChangeOneDay',
  'ownersChangeOneWeek',
  'ownersChangeOneMonth',
  'ownersChangeThreeMonths',
  'ownersChangeThisYear',
  'ownersChangeOneYear',
  'ownersChangeOneDayAbsolute',
  'ownersChangeOneWeekAbsolute',
  'ownersChangeOneMonthAbsolute',
  'ownersChangeThreeMonthsAbsolute',
  'ownersChangeThisYearAbsolute',
  'ownersChangeOneYearAbsolute',
  'macdValue',
  'macdHistogram',
  'macdSignal',
  'operatingCashFlow',
] as const;

const stock = z.looseObject({
  orderbookId: z.string(),
  companyId: z.string(),
  type: z.string(),
  name: z.string(),
  shortName: z.string(),
  currency: z.string(),
  countryCode: z.string(),
  marketPlaceCode: z.string(),
  hasPosition: z.boolean().optional(),
  hasAnalysis: z.boolean().optional(),
  nextCompanyReport: z.string().optional(),
  nextDividend: z.string().optional(),
  ...Object.fromEntries(metricNames.map((metric) => [metric, z.number().optional()])),
});

export const screenStocksResponseSchema: z.ZodType<ScreenStocksResponse> = z.looseObject({
  stocks: z.array(stock),
  filter: stockFilterSchema,
  pagination: z.object({ offset: z.number(), limit: z.number() }),
  sortBy: z.object({ field: z.string(), order: z.enum(['asc', 'desc']) }),
  totalNumberOfOrderbooks: z.number(),
  filterOptions: stockFilterOptionsSchema,
});

export const savedFiltersSchema = z.looseObject({
  filters: z.array(z.looseObject({ name: z.string(), filter: stockFilterSchema })),
});

export const screenerTabsSchema = z.looseObject({
  tabs: z.array(z.looseObject({ name: z.string(), columns: z.array(z.string()) })),
});

export const screenerMetadataSchema = z.looseObject({
  metadata: z.record(z.string(), z.unknown()),
});

const sector = z.looseObject({ sectorId: z.string(), sectorName: z.string() });
export const popularStockSectorsSchema = z.array(sector.extend({ illustrationName: z.string() }));
export const stockSectorGroupsSchema = z.array(
  z.looseObject({ sector, children: z.array(sector) }),
);
