import { AvanzaClient, AvanzaClientOptions } from "./client/AvanzaClient";
import type {
  AccountType,
  AccountsOverviewResponse,
  AuthenticateBankIDResponse,
  AuthenticateBankIDStatusResponse,
  AuthenticateBankIDStatusResponseActive,
  AuthenticateBankIDStatusResponseComplete,
  AuthenticationSessionTOPTResponse,
  BankIDAuthState,
  InstrumentPosition,
  InstrumentType,
  Position,
  PositionResponse,
  ErrorMessage,
} from "./client/types";
import type {
  SearchResponse,
  Hit,
  TopHit,
  Link,
  PageSearchResults,
  Dividend,
  HistoricalClosingPrices,
  InstrumentResponse,
  KeyIndicators,
  Listing,
  PreviousReport,
  PriceValue,
  Sector,
} from "./client/market_types";

export { AvanzaClient };
export type { AvanzaClientOptions };
export type {
  ErrorMessage,
  AccountType,
  AccountsOverviewResponse,
  AuthenticateBankIDResponse,
  AuthenticateBankIDStatusResponse,
  AuthenticateBankIDStatusResponseActive,
  AuthenticateBankIDStatusResponseComplete,
  AuthenticationSessionTOPTResponse,
  BankIDAuthState,
  InstrumentPosition,
  InstrumentType,
  Position,
  PositionResponse,
  SearchResponse,
  Hit,
  TopHit,
  Link,
  PageSearchResults,
  Dividend,
  HistoricalClosingPrices,
  InstrumentResponse,
  KeyIndicators,
  Listing,
  PreviousReport,
  PriceValue,
  Sector,
};
